name: olachat_mobile
description: "A new Flutter project. (OlaChat Mobile App)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  # Icons
  cupertino_icons: ^1.0.8
  #  Provider
  provider: ^6.1.2
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # Lib Logo APP
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Logo APP
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/